//export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_TASK = "UPDATE_TASK";
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_TASK = "ADD_TASK";
export const ADD_COMMENT = "ADD_COMMENT";
export const QUERY_PROJECT = "QUERY_PROJECT";
export const UPDATE_CURRENT_PROJECT = "UPDATE_CURRENT_PROJECT";

